# 配置文件

# 类型格式定义见： typings/config.d.ts
# 表情见：https://bj.96weixin.com/emoji

# 功能：给女朋友发早安和土味情话
loveMsg:
  # ✅
  # 重要信息
  #
  # 与女朋友相识的日子
  start_stamp: 2021-03-26
  # 女朋友所在城市（不要带‘市’），天气接口需要使用
  city_name: 蚌埠
  # 女朋友的爱称
  girl_name: 鱼崽
  # 对自己的称呼
  boy_name: 崽崽
  # 农历信息（默认开启）
  date_lunarInfo: true
  # 卡片中显示随机一句情话
  random_love: true
  # 点击卡片详情地址
  card_url: https://api.vvhan.com/api/60s

  # 🎈
  # 天气信息
  # ！！！卡片内容字节限制可能显示不完全
  #
  # 天气生活指数提示（默认关闭）
  weather_tips: false
  #
  # 极端天气温度提醒
  #
  # 低温提醒: 是否开启
  weather_low_show: true
  # 低温提醒: 0 => 最低温度低于 0℃ 时触发
  weather_low_tem: 5
  # 低温提醒: 提醒内容，这里的 {low} 为固定替换温度值
  # 支持数组形式：默认随机取其中一条消息发送，一条消息时固定发送本条消息（['消息1', '消息2','消息3']）
  # 如果要使换行符 \n 生效，需要使用双引号 ""
  weather_low_message:
    - "❄️啦啦啦~这里是来自崽崽的暖心提醒哦：\n今日最低温度仅为🥶 {low}，可冷可冷了~鱼崽崽可要注意保暖哦~"

  # 高温提醒: 是否开启
  weather_hight_show: true
  # 高温提醒: 30 => 最高温度高于 30℃ 时触发
  weather_hight_tem: 30
  # 高温提醒: 提醒内容，这里的 {hight} 为固定替换温度值
  weather_hight_message:
    - "🔥啦啦啦~这里是来自崽崽的暖心提醒哦：\n今日最高温度高达🥵 {hight}，这也忒热了~鱼崽崽可要注意防暑哦~"

  # 🧡
  # 纪念日
  #
  # 需要提醒的纪念日: 相恋日期
  memorial_day: 2021/03/26
  # 需要提醒的纪念日: 是否开启
  memorial_day_show: true
  # 需要提醒的纪念日: 提醒内容，这里的 {day} 为固定替换模板，不可更改
  memorial_day_message: 👫还有{day}天就是我们的恋爱纪念日啦~
  # 需要提醒的纪念日: 提醒内容，当天
  memorial_day_message_now: 👫执子之手，与子偕老。宝~，今天可是我们恋爱{year}周年啦
  # 需要提醒的纪念日: 倒计时多久时开始提醒，单位天
  memorial_day_day: 52

  # 👧
  # 女朋友生日
  #
  # 女朋友的生日: 是否开启
  girl_birthday_show: true
  # 女朋友的生日: 12月15日
  girl_birthday_date: 12/25
  # 女朋友的生日: 提醒内容，这里的 {day} 为固定替换模板，不可更改
  girl_birthday_message: 👧🏻还有{day}天就是鱼崽崽的生日啦~
  # 女朋友的生日: 提醒内容，当天
  girl_birthday_message_now: 👧🏻身无彩凤双飞翼，心有灵犀一点通。鱼崽崽~，生日快乐哦🎂，今天可是我宝的生日🤗~
  # 女朋友的生日: 倒计时多久时开始提醒，单位天
  girl_birthday_day: 52

  # 👦
  # 男朋友生日
  #
  # 男朋友的生日: 是否开启
  boy_birthday_show: true
  # 男朋友的生日: 3月21日
  boy_birthday_date: 03/21
  # 男朋友的生日: 提醒内容，这里的 {day} 为固定替换模板，不可更改
  boy_birthday_message: 👦🏻还有{day}天就是帅崽崽的生日啦~
  # 男朋友的生日: 提醒内容，当天
  boy_birthday_message_now: 👦🏻忆君心似西江水 日夜东流无歇时。帅崽崽~，生日快乐哦🎂，今天可是我宝的生日🤗~
  # 男朋友的生日: 倒计时多久时开始提醒，单位天
  boy_birthday_day: 52

  #
  # 我的自定义情话、消息
  # - 默认随机取其中一条消息发送：模板 => ['消息1', '消息2','消息3']
  # - 如要你想固定发送某一条消息，就只保留这一条即可
  # - 如果要使换行符 \n 生效，需要使用双引号 ""
  #
  # ！！！彩蛋！！！注意
  # - 彩蛋：当随机到时，会再次随机一次，需要连续两次随机到才会出现，好运，嘿嘿~😁(概率大概为)
  # - 🎃注意：如何辨别彩蛋？存在关键字“彩蛋”的消息，会被认为一条彩蛋
  # - 🎃生日当天必出现的信息，根据排序筛选: 女友生日 => 倒数第二条，男友生日 => 倒数第一条
  #
  my_love_message_show: true
  # 为确保随机的概率相对稳定，需要设定一个固定值
  # 设置彩蛋的概率最大公约数为64，即约 1/64 的概率
  my_love_message_egg_probability: 64
  # 自定义情话内容
  my_love_message_content:
    - 💌宝啊~，你猜我是今天想你多一点、还是昨天想你多一点呢🥰
    - 💌喂喂喂~，我的臭宝在吗~
    - "💌臭宝~今天打算干啥呀？\n😁看到消息要第一时间回我哦~，我会很期待的😛~"
    - 💌长江长江！！！我是黄河！！！听到请回答~
    - 💌水果？零食？统统买给我~
    - 💌今天你要主动联系我哦~
    - 💌宝~，我养你啊~
    # 最后两条信息是作为生日彩蛋必须要存在的，请至少保证这两条信息存在
    - "🎉【注意啦，彩蛋触发~】叮叮叮~：\n当这条消息出现时，今天帅崽崽就是大姐的男人😆，要好好表现哦，奶茶、水果整起来~"
    - "🎉【注意啦，彩蛋触发~】啦啦啦~：\n当这条消息出现时，今天鱼崽崽就是大哥的女人😆，要好好表现哦，奶茶、水果整起来~"
