# 配置文件

# 功能：给女朋友发早安和土味情话
loveMsg:
  # 与女朋友相识的日子
  start_stamp: 2021-03-26
  # 女朋友所在城市（不要带‘市’）
  city_name: 蚌埠
  # 对女朋友的爱称
  girl_name: 鱼崽
  # 女朋友的生日 12月15日
  girl_birthday: 12/15
  # 女朋友的生日 倒计时多久时开始提醒，单位天
  girl_birthday_show: 30
  # 对自己的称呼
  boy_name: 崽崽
  # 点击卡片详情地址
  card_url: https://api.vvhan.com/api/60s
  # 农历信息（默认开启）
  date_lunarInfo: true
  # 随机一句情话
  random_love: true
  #
  # ！！！卡片内容字节限制可能显示不完全
  #
  # 天气生活指数提示（默认关闭）
  weather_tips: false
  # 极端天气温度提醒（默认开启）
  weather_tem: true
